apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./kubernetes/*
build:
  local:
    push: true
  artifacts:
    - image: client
      custom:
        buildCommand: ./build_client.sh
    - image: query
      custom:
        buildCommand: ./build_queryservice.sh
    - image: posts
      custom:
        buildCommand: ./build_posts.sh
    - image: comments
      custom:
        buildCommand: ./build_comments.sh
    - image: moderation
      custom:
        buildCommand: ./build_moderation.sh
    - image: eventbus
      custom:
        buildCommand: ./build_eventbus.sh
