apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - ./kubernetes/*
build:
  local:
    push: false
  artifacts:
    - image: client
      context: .
      custom:
        buildCommand: ./build_client_dev.sh
        dependencies:
          paths:
            - "/client/*"
      sync:
        manual:
          - src: "client/src/*"
            dest: .
    - image: query
      context: .
      custom:
        buildCommand: ./build_queryservice.sh
      sync:
        manual:
          - src: "queryservice/src/**/*.ts"
            dest: .
    - image: posts
      context: .
      custom:
        buildCommand: ./build_posts.sh
      sync:
        manual:
          - src: 'posts/src/**/*.ts'
            dest: .
    - image: comments
      context: .
      custom:
        buildCommand: ./build_comments.sh
        dependencies:
          paths:
            - "/comments/*"
      sync:
        manual:
          - src: 'comments/src/**/*.ts'
            dest: .
    - image: moderation
      context: .
      custom:
        buildCommand: ./build_moderation.sh
        dependencies:
          paths:
            - "/moderation/*"
      sync:
        manual:
          - src: 'moderation/src/**/*.ts'
            dest: .
    - image: eventbus
      context: .
      custom:
        buildCommand: ./build_eventbus.sh
        dependencies:
          paths:
            - "/eventbus/*"
      sync:
        manual:
          - src: 'eventbus/src/**/*.ts'
            dest: .
