apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msposts
  template:
    metadata:
      labels:
        app: msposts
    spec:
      containers:
        - name: msposts
          image: posts
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: msposts
  ports:
    - name: msposts
      protocol: TCP
      port: 2002
      targetPort: 2002